# Generated by Django 5.2 on 2025-05-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Task')),
                ('additional', models.TextField(blank=True, null=True, verbose_name='Additional information')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('completion_time', models.DateTimeField(blank=True, null=True, verbose_name='Completion time')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.theme', verbose_name='Theme')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['is_completed', '-creation_time'],
            },
        ),
    ]
