# Generated by Django 5.2 on 2025-05-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='additional',
            field=models.TextField(null=True, verbose_name='Дополнительная информация'),
        ),
    ]
