# Generated by Django 5.2 on 2025-05-11 15:23

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[tasks.models.validate_reserved_values]),
        ),
    ]
