# Generated by Django 5.2 on 2025-05-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='additional',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
