# Generated by Django 5.2 on 2025-05-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_completion_time_task_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', '-creation_time'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
